repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-json
  - id: check-yaml
  - id: pretty-format-json
    args: [--autofix]
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
    exclude: ^charts
  - id: pretty-format-toml
    args: [--autofix]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.9
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format
